title: Opia World
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

logo: "assets/images/opia.png"

url: https://just-the-docs.github.io

aux_links:
  RU: https://opia-world.github.io
  Opia World: https://opia-world.com
